### ISSUE TITLE
How can I trigger the chatbot window using a custom button/hook?

### ISSUE THREAD

**Issue by baharalidurrani** [watson-developer-cloud/assistant-web-chat-react#14]
What if I don’t want to use the default launcher button to open the main Watson messaging window?

How can I open/close the main window using a custom button or a react hook?

**Comment by TazmanianDI** [comment]
We have a tutorial on how to implement a custom launcher: https://github.com/watson-developer-cloud/assistant-toolkit/tree/master/integrations/webchat/examples/custom-launcher

Also, creating a GitHub issue isn't really the right way to ask questions. These are meant for reporting bug or issues with this library. If you have questions about web chat, you can ask in the IBM Watson Assistant community: https://community.ibm.com/community/user/watsonai/communities/community-home/digestviewer?CommunityKey=7a3dc5ba-3018-452d-9a43-a49dc6819633

Or you can always try asking a question on stackoverflow and tag it with `watson-assistant`.

**Comment by baharalidurrani** [comment]
Thank you @TazmanianDI.
If someone else is facing the same issue, the following is my solution to this problem:

`WatsonInit.ts`
```ts
import { WebChatConfig, WebChatContainer } from '@ibm-watson/assistant-web-chat-react';

export function WatsonLib({ setWatsonInstance }: { setWatsonInstance: (instance: any) => void }) {
  /**
   * This is the web chat config that is provided by the host page that is passed to web chat (usually through
   * window.watsonAssistantChatOptions. The actual values available here can vary depending on the version of web chat
   * being used. You can find the official documentation for these config options here:
   * https://web-chat.global.assistant.watson.cloud.ibm.com/docs.html?to=api-configuration.
   */
  const webChatOptions: WebChatConfig = {
    integrationID: process.env.REACT_APP_WATSON_ASSISTANT_INTEGRATION_ID ?? '', // The ID of this integration.
    region: (process.env.REACT_APP_WATSON_ASSISTANT_REGION as any) ?? 'us-south', // The region your integration is hosted in.
    serviceInstanceID: process.env.REACT_APP_WATSON_ASSISTANT_SERVICE_INSTANCE_ID, // The ID of your service instance.
    // subscriptionID: 'only on enterprise plans',
    // Note that there is no onLoad property here. The WebChatContainer component will override it with its own.
    showLauncher: false,
    showCloseAndRestartButton: true,
  };
  return (
    <WebChatContainer
      onBeforeRender={async (instance) => {
        setWatsonInstance(instance);
      }}
      config={webChatOptions}
    />
  );
}
```

After loading the library, we can use the `instance.toggleOpen()` method to open/close the chatbot from anywhere in our app.
`TriggerButton.tsx`
```tsx
import React, { useState } from 'react';
import { WatsonLib } from '../WatsonLib';

export function TriggerButton() {
  const [watsonInstance, setWatsonInstance] = useState<{ [keys: string]: any }>();
  return (
    <>
      <WatsonLib setWatsonInstance={setWatsonInstance} />
      <button onClick={watsonInstance?.toggleOpen}>
        Toggle Watson
      </button>
    </>
  );
}

```

**Comment by TazmanianDI** [comment]
Just because I can't help myself :-), but there is a tiny simplification you can make in there. You can change
```
onBeforeRender={async (instance) => {
  setWatsonInstance(instance);
}}
```
to
```
onBeforeRender={setWatsonInstance}
````

You can also change
```
useState<{ [keys: string]: any }>()
```
to
```
useState<WebChatInstance>()
```
The `WebChatInstance` interface should be exported by our library.
