### ISSUE TITLE
Invalid integrationID error with react component but script copied from Integrations page works

### ISSUE THREAD

**Issue by afrolab** [watson-developer-cloud/assistant-web-chat-react#26]
I'm getting the error `[IBM watsonx Assistant WebChatContainer] An error occurred loading web chat Error: [IBM watsonx Assistant Chat] The value of integrationID "XXXX" is not a valid ID.` when using the assistant-web-chat-react component.  However, if I create a simple web page with the embed code copied from the watsonx Assistant Integrations page, the agent loads fine.

I've double checked the integrationID, region, and serviceInstanceID values being passed to the react component and they are the same as in my simple web page I made.

Can you please help me resolve? I'd really like to use the assistant chat in my react app.

**Comment by TazmanianDI** [comment]
I would double check that there isn't something weird about the ID as you've pasted it into your React app. Is there any unexpected whitespace in it like a space at the beginning or end? Or maybe the `-` character is the wrong character? If you copy the ID from some different kinds of editors, maybe it changed the dash from the normal ASCII to one of the enhanced/extended dashes.

Here is the code that web chat uses to validate the ID. You could paste this in your code and put the ID through it and see if this is returning false and if it is, you can dig into the regexp here more carefully to see if you can figure out what's wrong.

```
function isValidUUID(id) {
  return (
    typeof id === 'string' && id.match(/^[0-9a-f]{8}-?[0-9a-f]{4}-?[0-9a-f]{4}-?[0-9a-f]{4}-?[0-9a-f]{12}$/i) !== null
  );
}
```
