### ISSUE TITLE
Using instance.send does not update the messages in the webchat.

### ISSUE THREAD

**Issue by stepoibm** [watson-developer-cloud/assistant-web-chat-react#30]
Hi!

We are trying to send a message to Watson Assistant from another component in the website. The Agent component right now looks like this:

```
import style from './Agent.module.scss';
import {
  setEnableDebug,
  WebChatCustomElement,
  WebChatInstance,
} from '@ibm-watson/assistant-web-chat-react';
import React, { useState } from 'react';
import { Button, Loading } from '@carbon/react';

const Agent = () => {
  const [instance, setInstance] = useState<undefined | WebChatInstance>(undefined);

  const onBeforeRender = async (renderedInstance: WebChatInstance) => {
    if (instance === undefined) {
      setInstance(renderedInstance);
    }
  };

  setEnableDebug(true);

  return region !== undefined ? (
    <div style={{ height: '100%' }}>
      <WebChatCustomElement
        className={style.AgentContainer}
        config={{
          integrationID: "XX",
          region: "XX",
          instanceId: "XX",
          showRestartButton: true,
        }}
        onBeforeRender={(instance) => onBeforeRender(instance)}
      />
      <Button onClick={() => instance!.send('hello')}>Send Hello</Button>
    </div>
  ) : (
    <Loading />
  );
};

export default Agent;
```

I expect the "Hello" to appear in the Assistant chat when the "Send Hello" button is clicked. 

However the sent message and WA response only show up on page reload. 

What am I missing?

Thank you!

**Comment by stepoibm** [comment]
Here's a quick screencap of the issue. 
[bug.webm](https://github.com/user-attachments/assets/44126978-146f-4811-ad3b-277c9653f5c7)

I see the message being sent over the network. It's identical to the message being sent if I use the input.

**Comment by stepoibm** [comment]
Alright, I think I figured it out. It's this:

```
if (instance === undefined) {
      setInstance(renderedInstance);
}
```

If I remove the if clause, there's an infinite loop, because WebChat gets rerendered on a setInstance. If I leave it in, the reference to instance is wrong. 

I have to use instanceRef instead.

**Comment by TazmanianDI** [comment]
Actually I think the problem is that you're passing a new config object to `WebChatCustomElement` on each render (it's a new instance of the object but the values are the same) and web chat detects that as a change in the config and so it reloads. Web chat does not do a deep comparison of the config object to detect changes. You should move the config object out of the render body of the component and make it an external constant.

**Comment by stepoibm** [comment]
You're right of course. I've been using a hook to fetch the environment variables from a backend. That hook always returns a copy of the config object when called. Thanks for your help!
