### ISSUE TITLE
How to capture the identityTokenExpired expired event in React

### ISSUE THREAD

**Issue by roberso** [watson-developer-cloud/assistant-web-chat-react#31]
When I use the standard HTML version of importing the web chat and I want to push and identity token into the assistant session, I use the following:in the watsonAssistantChatOptions:
```
			onLoad: async (instance) => {
				instance.on({
					type: 'identityTokenExpired',
					handler: async (event) => {
						const jwtFromServer = await fetch('/api/v1/core/jwt');
						const jwt = await jwtFromServer.json()
```

In the react version of the widget, that option is not allowed.  I can get the instance and call the updateIdentityToken, that works until the token expires, then the chat breaks.
```
        if (instance) {
            API.getJWT().then(jwt => {
                instance.updateIdentityToken(jwt.token)
            }).catch(err => console.error('jwt',err))
        }
```

So, using the react widget, how do I listen for the identityTokenExpired event?

**Comment by TazmanianDI** [comment]
In the React library, you can use the [onBeforeRender](onBeforeRender) prop to pass a callback that will return you the instance and from there, you can add the listener just like you were in the regular html version.

**Comment by roberso** [comment]
@TazmanianDI Would you mind providing sample code on what that would look like?

**Comment by TazmanianDI** [comment]
There is a `function onBeforeRender(instance, setInstance)` example function in the docs I linked above. Just copy the call that does the `instance.on` from your original example to inside that function.
